"""initial schema: cases and case_steps

Revision ID: e9aa103c2b34
Revises: 
Create Date: 2026-08-24 18:10:42.974868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9aa103c2b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('vertical', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('ltv_tier', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('raw_failure_reason', sa.String(length=255), nullable=False),
    sa.Column('diagnosis', sa.String(length=64), nullable=False),
    sa.Column('vertical_metadata', sa.JSON(), nullable=False),
    sa.Column('amount_recovered', sa.Float(), nullable=False),
    sa.Column('cost_of_recovery', sa.Float(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('latest_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_cases_customer_vertical', ['customer_id', 'vertical'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_next_followup_at'), ['next_followup_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index('ix_cases_status_priority', ['status', 'priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_vertical'), ['vertical'], unique=False)

    op.create_table('case_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('decision_source', sa.String(length=32), nullable=False),
    sa.Column('llm_call_made', sa.Boolean(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=False),
    sa.Column('proposed_action', sa.String(length=64), nullable=False),
    sa.Column('final_action', sa.String(length=64), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('guardrail_verdict', sa.String(length=16), nullable=False),
    sa.Column('guardrail_reason', sa.String(length=255), nullable=True),
    sa.Column('action_status', sa.String(length=32), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('recovered_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_steps_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_case_steps_case_step', ['case_id', 'step_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_case_steps_intent_id'), ['intent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_steps_intent_id'))
        batch_op.drop_index('ix_case_steps_case_step')
        batch_op.drop_index(batch_op.f('ix_case_steps_case_id'))

    op.drop_table('case_steps')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_vertical'))
        batch_op.drop_index('ix_cases_status_priority')
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_priority_score'))
        batch_op.drop_index(batch_op.f('ix_cases_next_followup_at'))
        batch_op.drop_index(batch_op.f('ix_cases_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_cases_event_id'))
        batch_op.drop_index('ix_cases_customer_vertical')
        batch_op.drop_index(batch_op.f('ix_cases_customer_id'))

    op.drop_table('cases')
    # ### end Alembic commands ###
